name: cloudrelay
description: "Professional Cloud Deployment Automation Tool for GitHub."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # Network & API
  http: ^1.1.0
  url_launcher: ^6.2.5 # إضافة المكتبة المفقودة
  
  # File Processing & Storage
  archive: ^3.4.9
  path_provider: ^2.1.2
  file_picker: ^8.1.2
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
